config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :wines do
    resources :orders
    collection do
      get 'search'
      post 'search'
    end
  end
  root 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :all                   # allow everyone to read everything
    if user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard, :manage, :update, :all          # allow access to dashboar
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cust_order.rb
class CustOrder < ApplicationRecord
  belongs_to :wine
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :wine
  validates :cust_name, :email, :address,
            :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  def self.from_omniauth(auth)
   # Case 1: Find existing user by facebook uid
   user = User.find_by_fb_uid( auth.uid )
   if user
      user.fb_token = auth.credentials.token
      #user.fb_raw_data = auth
      user.save!
      return user
   end

   # Case 2: Find existing user by email
   existing_user = User.find_by_email( auth.info.email )
   if existing_user
     existing_user.fb_uid = auth.uid
     existing_user.fb_token = auth.credentials.token
     #existing_user.fb_raw_data = auth
     existing_user.save!
     return existing_user
   end

   # Case 3: Create new password
   user = User.new
   user.fb_uid = auth.uid
   user.fb_token = auth.credentials.token
   user.email = auth.info.email
   user.password = Devise.friendly_token[0,20]
   #user.fb_raw_data = auth
   user.save!
   return user
  end
end

app/models/wine.rb
class Wine < ApplicationRecord
  has_many :orders, :dependent => :destroy
  validates :name, :description, :year, :price,
            presence: true
  has_attached_file :image, styles: { large: "350x500", medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cust_orders_controller.rb
class CustOrdersController < ApplicationController
  def index
  end

end

app/controllers/custorders_controller.rb
class CustordersController < ApplicationController
  def index
    @orders = Wine.find(params[:id]).Custorders.all
  end

  def show
  end

  def new
    @wine = Wine.find(params[:id])
    @order = @wine.custorders.build
  end

  def create
    @wine = Wine.find(params[:wine_id])
    @order = @wine.custorders.new(custorder_params)

    if @order.save
      redirect_to wine_path(params[:wine_id])
    else
      render 'new'
    end
  end

  def edit
    @wine = Wine.find(params[:wine_id])
    @order = @wine.find(params[:id])
  end

  def update
    @wine = Wine.find(params[:wine_id])
    @order = @wine.find(params[:id])

    if @order.update
      redirect_to wine_path(@wine)
    else
      render 'edit'
  end

  def destroy
    @wine = Wine.find(params[:wine_id])
    @order = @wine.custorders.find(params[:id])
    @order.destroy
    redirect_to wine_path(@wine)
  end

  private

  def custorder_params
    params.require(:custorder).permit(:cust_name, :email, :address, :wine_id, :quantity)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @wine = Wine.find(params[:wine_id])
    redirect_to new_wine_order_path
  end

  def show
  end

  def new
    @wine = Wine.find(params[:wine_id])
    @order = @wine.orders.build
  end

  def create
    @wine = Wine.find(params[:wine_id])
    @order = @wine.orders.new(order_params)

    if @order.save
      redirect_to wine_path(params[:wine_id])
    else
      render 'new'
    end
  end

  def edit
    @wine = Wine.find(params[:wine_id])
    @order = @wine.find(params[:id])
  end

  def update
    @wine = Wine.find(params[:wine_id])
    @order = @wine.find(params[:id])

    if @order.update
      redirect_to wine_path(@wine)
    else
      render 'edit'
    end
  end

  def destroy
    @wine = Wine.find(params[:wine_id])
    @order = @wine.orders.find(params[:id])
    @order.destroy
    redirect_to wine_path(@wine)
  end

  private

  def order_params
    params.require(:order).permit(:cust_name, :email, :address, :wine_id, :quantity)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # raise "routes found"
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to wines_path
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  include CanCan::ControllerAdditions
  before_action :set_wine, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  def index
    @wine = Wine.all
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      redirect_to wines_path
      flash[:notice] = "You've published your post successfully."
    else
      render 'new'
    end
  end

  def search
    @searched_value = params[:search]
    @wine = Wine.where("name LIKE ? OR description LIKE ? OR year LIKE ? ",
     "%#{@searched_value}%", "%#{@searched_value}%", "%#{@searched_value}%")
  end

  def edit
  end

  def show
  end

  def update

  end

  def destroy
    @wine.destroy
    redirect_to wines_path
  end
private
  def set_wine
    @wine = Wine.find(params[:id])
  end

  def wine_params
    params.require(:wine).permit(:name,:type,:description,:year,:price, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cust_orders_helper.rb
module CustOrdersHelper
end

app/helpers/custorders_helper.rb
module CustordersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>The Wine Guy</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    </head>

    <body>
        <!-- <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p> -->
        <header class="navbar page-icon">
            <%= link_to '<span class="glyphicon glyphicon-home" aria-hidden="true"></span>'.html_safe, wines_path, class: "btn btn-default pull-left home-btn" %>
            <div class="navbar-form navbar-right" id="login-links">
              <% if current_user %>
              <%= link_to('Log Out', destroy_user_session_path, :method => :delete, class: "btn btn-primary") %>
              <%= link_to('Change Password', edit_user_registration_path, class: "btn btn-default") %>
                <% else %>
              <%= link_to('Sign Up', new_user_registration_path, class: "btn btn-success") %>
              <%= link_to('Sign In', new_user_session_path, class: "btn btn-primary") %>
              <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
              <% end %>
            </div>
        </header>
        <nav class="navbar navbar-default">
            <div class="website-title">The Wine Guys</div>
              <div class="form-group">
                  <%= bootstrap_form_for :search, url: search_wines_path, method: "POST", class: "input-field" do |f| %>
                  <%= text_field_tag :search, nil, placeholder: " Search by name, description, year..." %>
                  <%= submit_tag 'Search', class: "btn btn-default"%>
                  <% end %>
              </div>
        </div>
    </nav>

    <%= yield %>
</body>
</html>

app/views/orders/_form.html.slim
= bootstrap_form_for [@wine, @order], validate: true do |f|
  = f.text_field :cust_name, label: "Name", class: "cust-name"
  
  = f.text_field :email, class: "email"
  
  = f.text_area :address, class: "order-address"
  
  = f.number_field :quantity, class: "order-quantity"
  = f.submit 'Place Order', class: "btn btn-default wine-order"
  

= form_for @wine do |wine|

  = wine.number_field :price, class: "wine-price"

app/views/orders/edit.html.slim
h2 Edit Order
= render 'form'

app/views/orders/new.html.slim
div.order-form
  h2 Place New Order
  = render 'form'
  == link_to 'Back', wine_path(@wine), class: "btn btn-primary"

app/views/wines/_form.html.slim
= bootstrap_form_for @wine, html: {multipart: true }, validate: true do |f|
  
    = f.text_field :name

    = f.file_field :image
    
    = f.text_area :description

    = f.number_field :year

    = f.number_field :price
  
    = f.submit 'Add a new wine', class: "btn btn-default"

app/views/wines/create.html.slim
h1 Wines#create
p Find me in app/views/wines/create.html.slim

app/views/wines/destroy.html.slim
h1 Wines#destroy
p Find me in app/views/wines/destroy.html.slim

app/views/wines/edit.html.slim
div.edit-form
  h1 Edit your wine
  == render 'form'

  == link_to 'Go back', wine_path(@wine), class: "btn btn-primary"

app/views/wines/index.html.slim
section.container.page-container
  section.container.wine-container
  - @wine.each do |wine|
    .col-xs-4
      header.wine-image
        == image_tag wine.image.url(:medium)
      br /
      section.wine-name
        == wine.name
      br /
      section.wine-year
        == wine.year
      br /
      == link_to 'Look at this wine', wine_path(wine), class:"btn btn-info wine-info"
      hr /
      / == link_to 'Delete this wine', wine, method: :delete, data: { confirm: 'Are you sure?' }
    


/ == link_to 'Lets go and add a wine', new_wine_path

app/views/wines/new.html.slim
div.new-form
  h1 Add a new wine
  == render 'form'

  == link_to "Let's go back!", wines_path, class: "btn btn-primary"

app/views/wines/search.html.slim
section.container.page-container
  section.container.wine-container
  - @wine.each do |wine|
    .col-xs-4
      header.wine-image
        == image_tag wine.image.url(:medium)
      br /
      section.wine-name
        == highlight(wine.name, @searched_value)
      br /
      section.wine-year
        == highlight(wine.year, @searched_value)
      br /
      == link_to 'Look at this wine', wine_path(wine), class:"btn btn-info wine-info"
      hr /
      / == link_to 'Delete this wine', wine, method: :delete, data: { confirm: 'Are you sure?' }
    


/ == link_to 'Lets go and add a wine', new_wine_path

app/views/wines/show.html.slim
header.container.show-page-header
  == @wine.name 
  span &nbsp;
  == @wine.year
section.container.wine-contents
  section.col-xs-6
    = image_tag @wine.image.url(:large)
    br /
  section.col-xs-6
    span.wine_price
      == @wine.price
    br /
    == @wine.description
    br /
    
    hr /
    = link_to 'Place order', new_wine_order_path(@wine), class:"btn btn-success btn-order"
    span &nbsp;&nbsp;&nbsp;
    / == link_to 'Edit the wine', edit_wine_path
    br /
    == link_to 'Go back', wines_path, class: "btn btn-default btn-go-back"
 

app/views/wines/update.html.slim
h1 Wines#update
p Find me in app/views/wines/update.html.slim